ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS bg_light_color TEXT DEFAULT '#F8FAFC' NOT NULL;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS bg_dark_color TEXT DEFAULT '#020617' NOT NULL;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS card_light_color TEXT DEFAULT '#FFFFFF' NOT NULL;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS card_dark_color TEXT DEFAULT '#0F172A' NOT NULL;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS text_light_color TEXT DEFAULT '#0F172A' NOT NULL;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS text_dark_color TEXT DEFAULT '#F8FAFC' NOT NULL;
